name: http2_client
version: 1.0.2
description: A package:http BaseClient that speaks HTTP/2, and can maintain connections.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/http2_client
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  http: ^0.13.0
  http2: ^2.0.0
  tuple: ^2.0.0
dev_dependencies:
  angel3_framework: ^4.2.2
  cli_repl: ^0.2.0
  pedantic: ^1.0.0
  test: ^1.0.0